# Generated by Django 5.2.10 on 2026-02-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_data",
                        to="catalog.catalogproject",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("elevation", models.FloatField(blank=True, null=True)),
                (
                    "sort_order",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "stories",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("Wall", "Wall"),
                            ("Column", "Column"),
                            ("Beam", "Beam"),
                            ("Pier", "Pier"),
                            ("Link", "Link"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unique_name", models.CharField(blank=True, max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="projects.project",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elements",
                        to="projects.story",
                    ),
                ),
            ],
            options={
                "db_table": "elements",
                "ordering": ["element_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="LoadCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "case_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Time History", "Time History"),
                            ("Modal", "Modal"),
                            ("Static", "Static"),
                            ("Pushover", "Pushover"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_cases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "load_cases",
                "ordering": ["name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["project", "sort_order"], name="stories_project_3c8d16_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="story",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="element",
            index=models.Index(
                fields=["project", "element_type"], name="elements_project_7dea9c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="element",
            unique_together={("project", "element_type", "unique_name")},
        ),
    ]
