import {
  COMPARISON_SERIES_PALETTE,
  PROFILE_SERIES_PALETTE,
  ROTATION_COMPARISON_PALETTE,
} from './colors'

export const PROFILE_SERIES_COLORS = [...PROFILE_SERIES_PALETTE]

export const COMPARISON_SERIES_COLORS = [...COMPARISON_SERIES_PALETTE]

export const ROTATION_COMPARISON_COLORS = [...ROTATION_COMPARISON_PALETTE]
